#!/bin/sh
 
git filter-branch --env-filter '
 
an="Wachiwi"
am="speichermail2@aol.com"
cn="Wachiwi"
cm="speichermail2@aol.com"
 
if [ "$GIT_COMMITTER_EMAIL" = "speichermail2@aol.com" ]
then
    cn="Wachiwi"
    cm="speichermail2@aol.com"
fi
if [ "$GIT_AUTHOR_EMAIL" = "speichermail2@aol.com" ]
then
    an="Wachiwi"
    am="speichermail2@aol.com"
fi
 
export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'

